version: '3.8'

services:
  db:
    image: postgres:16-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -q -U ${DB_USERNAME}"
    volumes:
      - db_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:10.20-alpine
    command: -url=jdbc:postgresql://db:${DB_PORT}/${DB_NAME} -user=${DB_USERNAME} -password=${DB_PASSWORD} -schemas=${DB_SCHEMA} -connectRetries=60 migrate
    depends_on:
      - db
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
      - ./src/main/resources/flyway.conf:/flyway/conf/flyway.conf

volumes:
  db_data: